/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.formularios;

/**
 *
 * @author SATC
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLCadastroPaciente = new javax.swing.JLabel();
        jPCadastroPaciente = new javax.swing.JPanel();
        jLEstadoCivilPaciente = new javax.swing.JLabel();
        jLSexoPaciente = new javax.swing.JLabel();
        jTFSexoPaciente = new javax.swing.JTextField();
        jTFEstadoCivilPaciente = new javax.swing.JTextField();
        jTFnumSUS = new javax.swing.JTextField();
        jLNumSus = new javax.swing.JLabel();
        jLResponsavel = new javax.swing.JLabel();
        jTFResponsavelPaciente = new javax.swing.JTextField();
        jTFIdPaciente = new javax.swing.JTextField();
        jLIDPaciente = new javax.swing.JLabel();
        jTFEnderecoPaciente = new javax.swing.JTextField();
        jTFRGpaciente = new javax.swing.JTextField();
        jTFCPFpaciente = new javax.swing.JTextField();
        jTFNomePaciente = new javax.swing.JTextField();
        jTFDataNascimentoPaciente = new javax.swing.JTextField();
        jLNomePaciente = new javax.swing.JLabel();
        jDataNascimentoPaciente = new javax.swing.JLabel();
        jLEnderecoPaciente = new javax.swing.JLabel();
        jLRGPaciente = new javax.swing.JLabel();
        jLCPFPaciente = new javax.swing.JLabel();
        jLTelePaciente = new javax.swing.JLabel();
        jTFTelefonePaciente = new javax.swing.JTextField();
        jBCadastrarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLCadastroPaciente.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLCadastroPaciente.setText("  Cadastro de Paciente");

        jPCadastroPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEstadoCivilPaciente.setText("Estado Civil:");

        jLSexoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLSexoPaciente.setText("Sexo (M)(F):");

        jTFSexoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFSexoPaciente.setText(" ");

        jTFEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEstadoCivilPaciente.setText(" ");

        jTFnumSUS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFnumSUS.setText(" ");

        jLNumSus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLNumSus.setText("Número SUS:");

        jLResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLResponsavel.setText("Responsável:");

        jTFResponsavelPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFResponsavelPaciente.setText(" ");

        jTFIdPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFIdPaciente.setText("               ");
        jTFIdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdPacienteActionPerformed(evt);
            }
        });

        jLIDPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLIDPaciente.setText("ID Paciente:");

        jTFEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEnderecoPaciente.setText(" ");

        jTFRGpaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFRGpaciente.setText(" ");

        jTFCPFpaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFCPFpaciente.setText("   ");

        jTFNomePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFNomePaciente.setText(" ");

        jTFDataNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFDataNascimentoPaciente.setText("             ");

        jLNomePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLNomePaciente.setText("Nome:");

        jDataNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDataNascimentoPaciente.setText("Data de Nascimento: ");

        jLEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEnderecoPaciente.setText("Endereço:");

        jLRGPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLRGPaciente.setText("RG:");

        jLCPFPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCPFPaciente.setText("CPF:");

        jLTelePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTelePaciente.setText("Telefone:");

        jTFTelefonePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFTelefonePaciente.setText(" ");

        javax.swing.GroupLayout jPCadastroPacienteLayout = new javax.swing.GroupLayout(jPCadastroPaciente);
        jPCadastroPaciente.setLayout(jPCadastroPacienteLayout);
        jPCadastroPacienteLayout.setHorizontalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                                .addComponent(jLNomePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLCPFPaciente)
                                    .addComponent(jLEnderecoPaciente)
                                    .addComponent(jLRGPaciente)
                                    .addComponent(jLResponsavel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFResponsavelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCPFpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFRGpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSexoPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEstadoCivilPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNumSus, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTelePaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLIDPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDataNascimentoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFnumSUS)
                    .addComponent(jTFTelefonePaciente)
                    .addComponent(jTFSexoPaciente)
                    .addComponent(jTFEstadoCivilPaciente)
                    .addComponent(jTFIdPaciente)
                    .addComponent(jTFDataNascimentoPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPCadastroPacienteLayout.setVerticalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIDPaciente)
                    .addComponent(jLNomePaciente)
                    .addComponent(jTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFnumSUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNumSus)
                            .addComponent(jTFEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEnderecoPaciente))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRGPaciente)
                            .addComponent(jLTelePaciente)
                            .addComponent(jTFTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFRGpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)))
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEstadoCivilPaciente)
                        .addComponent(jTFSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLResponsavel)
                            .addComponent(jTFResponsavelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFEstadoCivilPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSexoPaciente)
                            .addComponent(jLCPFPaciente)
                            .addComponent(jTFCPFpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jBCadastrarPaciente.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCadastrarPaciente)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLCadastroPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarPaciente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCadastrarPaciente;
    private javax.swing.JLabel jDataNascimentoPaciente;
    private javax.swing.JLabel jLCPFPaciente;
    private javax.swing.JLabel jLCadastroPaciente;
    private javax.swing.JLabel jLEnderecoPaciente;
    private javax.swing.JLabel jLEstadoCivilPaciente;
    private javax.swing.JLabel jLIDPaciente;
    private javax.swing.JLabel jLNomePaciente;
    private javax.swing.JLabel jLNumSus;
    private javax.swing.JLabel jLRGPaciente;
    private javax.swing.JLabel jLResponsavel;
    private javax.swing.JLabel jLSexoPaciente;
    private javax.swing.JLabel jLTelePaciente;
    private javax.swing.JPanel jPCadastroPaciente;
    private javax.swing.JTextField jTFCPFpaciente;
    private javax.swing.JTextField jTFDataNascimentoPaciente;
    private javax.swing.JTextField jTFEnderecoPaciente;
    private javax.swing.JTextField jTFEstadoCivilPaciente;
    private javax.swing.JTextField jTFIdPaciente;
    private javax.swing.JTextField jTFNomePaciente;
    private javax.swing.JTextField jTFRGpaciente;
    private javax.swing.JTextField jTFResponsavelPaciente;
    private javax.swing.JTextField jTFSexoPaciente;
    private javax.swing.JTextField jTFTelefonePaciente;
    private javax.swing.JTextField jTFnumSUS;
    // End of variables declaration//GEN-END:variables
}
