/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.formularios;

/**
 *
 * @author SATC
 */
public class Medico extends javax.swing.JFrame {

    /**
     * Creates new form Medico
     */
    public Medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCadastroMedico = new javax.swing.JLabel();
        jPCadastroMedico = new javax.swing.JPanel();
        jLECMedico = new javax.swing.JLabel();
        jLSexoMedico = new javax.swing.JLabel();
        jTFEstadoCivilMedico = new javax.swing.JTextField();
        jTFSexoMedico = new javax.swing.JTextField();
        jTFEspecialidadeMedico = new javax.swing.JTextField();
        jLEspecialidadeMedico = new javax.swing.JLabel();
        jLSetorMedico = new javax.swing.JLabel();
        jTFSetorMedico = new javax.swing.JTextField();
        jTFCRMMedico = new javax.swing.JTextField();
        jLCrmMedico = new javax.swing.JLabel();
        jTFCPFMedico = new javax.swing.JTextField();
        jTFRGMedico = new javax.swing.JTextField();
        jTFNomeMedico = new javax.swing.JTextField();
        jTFEnderecoMedico = new javax.swing.JTextField();
        jTFDataNascimentoMedico = new javax.swing.JTextField();
        jLNomePaciente = new javax.swing.JLabel();
        jDataNascimentoMedico = new javax.swing.JLabel();
        jLEnderecoMedico = new javax.swing.JLabel();
        jLRGPaciente = new javax.swing.JLabel();
        jLCPFMedico = new javax.swing.JLabel();
        jLTeleMedico = new javax.swing.JLabel();
        jTFTelefoneMedico = new javax.swing.JTextField();
        jBCadastrarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLCadastroMedico.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLCadastroMedico.setText("Cadastro do Médico");

        jPCadastroMedico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLECMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLECMedico.setText("Estado Civil:");

        jLSexoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLSexoMedico.setText("Sexo (M)(F):");

        jTFEstadoCivilMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEstadoCivilMedico.setText(" ");

        jTFSexoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFSexoMedico.setText(" ");

        jTFEspecialidadeMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEspecialidadeMedico.setText(" ");

        jLEspecialidadeMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEspecialidadeMedico.setText("Especialidade:");

        jLSetorMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLSetorMedico.setText("Setor:");

        jTFSetorMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFSetorMedico.setText(" ");

        jTFCRMMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFCRMMedico.setText("               ");
        jTFCRMMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCRMMedicoActionPerformed(evt);
            }
        });

        jLCrmMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCrmMedico.setText("CRM:");

        jTFCPFMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFCPFMedico.setText(" ");

        jTFRGMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFRGMedico.setText(" ");

        jTFNomeMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFNomeMedico.setText("   ");

        jTFEnderecoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEnderecoMedico.setText(" ");

        jTFDataNascimentoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFDataNascimentoMedico.setText("             ");

        jLNomePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLNomePaciente.setText("Nome:");

        jDataNascimentoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDataNascimentoMedico.setText("Data de Nascimento: ");

        jLEnderecoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEnderecoMedico.setText("Endereço:");

        jLRGPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLRGPaciente.setText("RG:");

        jLCPFMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCPFMedico.setText("CPF:");

        jLTeleMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTeleMedico.setText("Telefone:");

        jTFTelefoneMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFTelefoneMedico.setText(" ");

        javax.swing.GroupLayout jPCadastroMedicoLayout = new javax.swing.GroupLayout(jPCadastroMedico);
        jPCadastroMedico.setLayout(jPCadastroMedicoLayout);
        jPCadastroMedicoLayout.setHorizontalGroup(
            jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroMedicoLayout.createSequentialGroup()
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNomePaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSetorMedico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEnderecoMedico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFSetorMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLSexoMedico))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroMedicoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLECMedico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLRGPaciente)
                            .addComponent(jLCPFMedico))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTFCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLEspecialidadeMedico)
                                .addGap(8, 8, 8))
                            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFRGMedico)
                                    .addComponent(jTFNomeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCrmMedico, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLTeleMedico, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)))))
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEstadoCivilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroMedicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPCadastroMedicoLayout.setVerticalGroup(
            jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCrmMedico)
                    .addComponent(jTFNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNomePaciente))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGPaciente)
                    .addComponent(jLTeleMedico)
                    .addComponent(jTFTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFRGMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEspecialidadeMedico)
                    .addComponent(jTFEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCPFMedico))
                .addGap(20, 20, 20)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLECMedico)
                            .addComponent(jTFEstadoCivilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEnderecoMedico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSetorMedico)
                            .addComponent(jTFSetorMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSexoMedico))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jBCadastrarMedico.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCadastroMedico)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCadastrarMedico)
                    .addComponent(jPCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCadastrarMedico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCRMMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCRMMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCRMMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarMedico;
    private javax.swing.JLabel jDataNascimentoMedico;
    private javax.swing.JLabel jLCPFMedico;
    private javax.swing.JLabel jLCadastroMedico;
    private javax.swing.JLabel jLCrmMedico;
    private javax.swing.JLabel jLECMedico;
    private javax.swing.JLabel jLEnderecoMedico;
    private javax.swing.JLabel jLEspecialidadeMedico;
    private javax.swing.JLabel jLNomePaciente;
    private javax.swing.JLabel jLRGPaciente;
    private javax.swing.JLabel jLSetorMedico;
    private javax.swing.JLabel jLSexoMedico;
    private javax.swing.JLabel jLTeleMedico;
    private javax.swing.JPanel jPCadastroMedico;
    private javax.swing.JTextField jTFCPFMedico;
    private javax.swing.JTextField jTFCRMMedico;
    private javax.swing.JTextField jTFDataNascimentoMedico;
    private javax.swing.JTextField jTFEnderecoMedico;
    private javax.swing.JTextField jTFEspecialidadeMedico;
    private javax.swing.JTextField jTFEstadoCivilMedico;
    private javax.swing.JTextField jTFNomeMedico;
    private javax.swing.JTextField jTFRGMedico;
    private javax.swing.JTextField jTFSetorMedico;
    private javax.swing.JTextField jTFSexoMedico;
    private javax.swing.JTextField jTFTelefoneMedico;
    // End of variables declaration//GEN-END:variables
}
