/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.interfaces;

import br.com.juan.objetos.Consulta;
import br.com.juan.objetos.Enfermeira;
import br.com.juan.objetos.Medico;
import br.com.juan.objetos.Paciente;
import br.com.juan.objetos.Pessoa;
import br.com.juan.objetos.Triagem;
import br.com.juan.singleton.SConsulta;
import br.com.juan.singleton.SEnfermeira;
import br.com.juan.singleton.SMedico;
import br.com.juan.singleton.SPaciente;
import br.com.juan.singleton.STriagem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JFConsulta extends javax.swing.JFrame {

    Consulta c;
    Triagem tr;
    Medico m;
    Paciente p;

    /**
     * Creates new form Consulta
     */
    public JFConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFDiagnostico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFCodigoDiagnostico = new javax.swing.JTextField();
        jBAddMedicamentos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFMedicamento = new javax.swing.JTextField();
        jCBAtestado = new javax.swing.JComboBox<>();
        jLMedicamentos = new javax.swing.JLabel();
        jBPacientes = new javax.swing.JButton();
        jBEnfermeiras = new javax.swing.JButton();
        jLTriagem = new javax.swing.JLabel();
        jBMedicos = new javax.swing.JButton();
        jBEscolhaMedico = new javax.swing.JButton();
        jBTriagem = new javax.swing.JButton();
        jBCadastrarConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Consulta Médica");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Diagnostico:");

        jTFDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Codigo Diagnostico:");

        jTFCodigoDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTFCodigoDiagnostico.setText(" ");

        jBAddMedicamentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBAddMedicamentos.setText("+");
        jBAddMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddMedicamentosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Médico:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Criar Atestado?");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Medicamentos:");

        jCBAtestado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCBAtestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Sim", "Não" }));
        jCBAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtestadoActionPerformed(evt);
            }
        });

        jBPacientes.setText("Pacientes cadastrados");
        jBPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPacientesActionPerformed(evt);
            }
        });

        jBEnfermeiras.setText("Enfermeira(o)s cadastrados");
        jBEnfermeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnfermeirasActionPerformed(evt);
            }
        });

        jLTriagem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTriagem.setText("Triagem");

        jBMedicos.setText("Medicos cadastrados");
        jBMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedicosActionPerformed(evt);
            }
        });

        jBEscolhaMedico.setText("Escolher medico");
        jBEscolhaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEscolhaMedicoActionPerformed(evt);
            }
        });

        jBTriagem.setText("Triagens cadastradas");
        jBTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTriagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEnfermeiras)
                            .addComponent(jBTriagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jLMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAddMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCodigoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLTriagem)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jBEscolhaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEscolhaMedico))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLTriagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCBAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAddMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBEnfermeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jBCadastrarConsulta.setText("Cadastrar");
        jBCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarConsulta)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBCadastrarConsulta))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarConsultaActionPerformed

        String diagnostico = "";
        try {
            diagnostico = this.jTFDiagnostico.getText();
        } catch (StringIndexOutOfBoundsException sioobe) {
            JOptionPane.showMessageDialog(this, "Caracteres inválidos no campo diagnostico");
        }

        int codigoDiagnostico = 0;
        if (!jTFCodigoDiagnostico.getText().isEmpty()) {
            try {
                codigoDiagnostico = Integer.parseInt(jTFCodigoDiagnostico.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Codigo do dianóstico é um valor inteiro!");
            }
        }

        Boolean atestado;
        c = new Consulta(tr, m, SConsulta.getInstance().getMedicamentos(), diagnostico, rootPaneCheckingEnabled, codigoDiagnostico);
    
        JOptionPane.showMessageDialog(this, c.toString());

    }//GEN-LAST:event_jBCadastrarConsultaActionPerformed

    private void jBPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPacientesActionPerformed

        SPaciente.getInstance().getPacientes().forEach((Paciente pa) -> {

            SPaciente.getInstance().getResponsavel().forEach((res) -> {
                JOptionPane.showMessageDialog(this, "Dados do Paciente: " + pa.toString());

                JOptionPane.showMessageDialog(this, "Dados do Responsável: " + res.toString());
            });

        });


    }//GEN-LAST:event_jBPacientesActionPerformed

    private void jCBAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtestadoActionPerformed
        switch (jCBAtestado.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Selecione um item");
                break;
            case 1:
                new JFAtestado().setVisible(true);
                break;
            case 2:

                break;

        }
    }//GEN-LAST:event_jCBAtestadoActionPerformed

    private void jBEnfermeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnfermeirasActionPerformed

        SEnfermeira.getInstance().getEnfermeiras().forEach((emf) -> {
            JOptionPane.showMessageDialog(this, "Dados do Enfermeiro(a)" + emf.toString());
        });

    }//GEN-LAST:event_jBEnfermeirasActionPerformed

    private void jBAddMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddMedicamentosActionPerformed
        String medicamento = this.jTFMedicamento.getText();
        List<String> medicamentos = new ArrayList();
        medicamentos.add(medicamento);
        String mdcs = "";
        for (String medics : medicamentos) {
            mdcs += "{" + medicamento + "}";
            jLMedicamentos.setText(mdcs);
        }


    }//GEN-LAST:event_jBAddMedicamentosActionPerformed

    private void jBMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedicosActionPerformed
        SMedico.getInstance().getMedicos().forEach((med) -> {
            JOptionPane.showMessageDialog(this, med.toString());
        });
    }//GEN-LAST:event_jBMedicosActionPerformed

    private void jBEscolhaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEscolhaMedicoActionPerformed
        String medCadastrados = "";
        for (Medico meds : SMedico.getInstance().getMedicos()) {
            medCadastrados += "\n" + SMedico.getInstance().getMedicos().indexOf(meds) + " " + meds.getNome();
            int escolhaMedico = Integer.parseInt(JOptionPane.showInputDialog("Informe a disciplina: \n " + medCadastrados));
            if (escolhaMedico != SMedico.getInstance().getMedicos().indexOf(meds)) {
                JOptionPane.showMessageDialog(null, "INVÁLIDO");
            } else {

            }
        }     }//GEN-LAST:event_jBEscolhaMedicoActionPerformed

    private void jBTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTriagemActionPerformed
        STriagem.getInstance().getTriagens().forEach((tri) -> {
            JOptionPane.showMessageDialog(this, tri.toString());
        });        // TODO add your handling code here:
    }//GEN-LAST:event_jBTriagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddMedicamentos;
    private javax.swing.JButton jBCadastrarConsulta;
    private javax.swing.JButton jBEnfermeiras;
    private javax.swing.JButton jBEscolhaMedico;
    private javax.swing.JButton jBMedicos;
    private javax.swing.JButton jBPacientes;
    private javax.swing.JButton jBTriagem;
    private javax.swing.JComboBox<String> jCBAtestado;
    private javax.swing.JLabel jLMedicamentos;
    private javax.swing.JLabel jLTriagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFCodigoDiagnostico;
    private javax.swing.JTextField jTFDiagnostico;
    private javax.swing.JTextField jTFMedicamento;
    // End of variables declaration//GEN-END:variables
}
