/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.interfaces;

import br.com.juan.objetos.Enfermeira;
import br.com.juan.singleton.SEnfermeira;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JFEnfermeira extends javax.swing.JFrame {
    Enfermeira e;

    /**
     * Creates new form Enfermeira
     */
    public JFEnfermeira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastroEnfermeira = new javax.swing.JPanel();
        jLECEnfermeira = new javax.swing.JLabel();
        jLSexoEnfermeira = new javax.swing.JLabel();
        jTFEstadoCivilEnfermeira = new javax.swing.JTextField();
        jTFSexoEnfermeira = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFSetorEnfermeira = new javax.swing.JTextField();
        jTFCofen = new javax.swing.JTextField();
        jLCofen = new javax.swing.JLabel();
        jTFCPFEnfermeira = new javax.swing.JTextField();
        jTFRGEnfermeira = new javax.swing.JTextField();
        jTFNomeEnfermeiro = new javax.swing.JTextField();
        jTFEnderecoEnfermeira = new javax.swing.JTextField();
        jTFDataNascimentoEnfermeira = new javax.swing.JTextField();
        jLNomeEnfermeira = new javax.swing.JLabel();
        jDataNascimentoEnfermeira = new javax.swing.JLabel();
        jLEnderecoEnfermeira = new javax.swing.JLabel();
        jLRGEnfermeira = new javax.swing.JLabel();
        jLCPFPaciente = new javax.swing.JLabel();
        jLTeleEnfermeira = new javax.swing.JLabel();
        jTFTelefoneEnfermeira = new javax.swing.JTextField();
        jLTituloEnfer = new javax.swing.JLabel();
        jBCadastrarEnfermeira = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPCadastroEnfermeira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLECEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLECEnfermeira.setText("Estado Civil:");

        jLSexoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLSexoEnfermeira.setText("Sexo (M)(F):");

        jTFEstadoCivilEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Setor:");

        jTFSetorEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCofen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFCofen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCofenActionPerformed(evt);
            }
        });

        jLCofen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCofen.setText("Cofen:");

        jTFCPFEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomeEnfermeiro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFDataNascimentoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLNomeEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLNomeEnfermeira.setText("Nome:");

        jDataNascimentoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDataNascimentoEnfermeira.setText("Data de Nascimento: ");

        jLEnderecoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEnderecoEnfermeira.setText("Endereço:");

        jLRGEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLRGEnfermeira.setText("RG:");

        jLCPFPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCPFPaciente.setText("CPF:");

        jLTeleEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTeleEnfermeira.setText("Telefone:");

        jTFTelefoneEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPCadastroEnfermeiraLayout = new javax.swing.GroupLayout(jPCadastroEnfermeira);
        jPCadastroEnfermeira.setLayout(jPCadastroEnfermeiraLayout);
        jPCadastroEnfermeiraLayout.setHorizontalGroup(
            jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                        .addComponent(jLSexoEnfermeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFSexoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDataNascimentoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDataNascimentoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroEnfermeiraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNomeEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEnderecoEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLRGEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLCPFPaciente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroEnfermeiraLayout.createSequentialGroup()
                                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCofen, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLTeleEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroEnfermeiraLayout.createSequentialGroup()
                                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                                        .addComponent(jTFEnderecoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLECEnfermeira))
                                    .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTFNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFCPFEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFRGEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroEnfermeiraLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTelefoneEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEstadoCivilEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCofen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSetorEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPCadastroEnfermeiraLayout.setVerticalGroup(
            jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCofen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCofen)
                    .addComponent(jTFNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNomeEnfermeira))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGEnfermeira)
                    .addComponent(jLTeleEnfermeira)
                    .addComponent(jTFTelefoneEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFRGEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCPFEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCPFPaciente)
                    .addComponent(jTFSetorEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLECEnfermeira)
                    .addComponent(jTFEstadoCivilEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEnderecoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEnderecoEnfermeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSexoEnfermeira)
                    .addComponent(jTFSexoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataNascimentoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDataNascimentoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jLTituloEnfer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLTituloEnfer.setText("Cadastro de Enfermeira(o)");

        jBCadastrarEnfermeira.setText("Cadastrar");
        jBCadastrarEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarEnfermeiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLTituloEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPCadastroEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarEnfermeira)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTituloEnfer)
                .addGap(18, 18, 18)
                .addComponent(jPCadastroEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jBCadastrarEnfermeira)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCofenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCofenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCofenActionPerformed

    private void jBCadastrarEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarEnfermeiraActionPerformed
        
        SimpleDateFormat sdf= new SimpleDateFormat("dd/mm/yyyy");
        String nomeEnfermeira = this.jTFNomeEnfermeiro.getText();
        String RGEnfermeira =this.jTFRGEnfermeira.getText();
        String CPFEnfermeira = this.jTFCPFEnfermeira.getText();
        String EnderecoEnfermeira = this.jTFEnderecoEnfermeira.getText();
        char sexo = this.jTFSexoEnfermeira.getText().toUpperCase().charAt(0);
        int Cofen = Integer.parseInt(this.jTFCofen.getText());
        String telefone = this.jTFTelefoneEnfermeira.getText();
        String setor = this.jTFSetorEnfermeira.getText();
        String EstadoCivilEnfermeira = this.jTFEstadoCivilEnfermeira.getText();
        Date DataNascimentoEnfermeira = new Date();
        try {
             DataNascimentoEnfermeira = sdf.parse(this.jTFDataNascimentoEnfermeira.getText());
        } catch (ParseException ex) {
            Logger.getLogger(JFEnfermeira.class.getName()).log(Level.SEVERE, null, ex);
        }
        e = new Enfermeira(Cofen, setor, nomeEnfermeira, telefone, CPFEnfermeira, RGEnfermeira, EnderecoEnfermeira, EstadoCivilEnfermeira, DataNascimentoEnfermeira, sexo);
         if ((jTFNomeEnfermeiro.getText().isEmpty()) || (jTFTelefoneEnfermeira.getText().isEmpty()) || (jTFCPFEnfermeira.getText().isEmpty())
                || (jTFRGEnfermeira.getText().isEmpty()) || (jTFEnderecoEnfermeira.getText().isEmpty()) || (jTFEstadoCivilEnfermeira.getText().isEmpty()) || (jTFDataNascimentoEnfermeira.getText().isEmpty()) || (jTFSexoEnfermeira.getText().isEmpty()))
              {
            JOptionPane.showMessageDialog(this, "Preencha os campos");

        } else {
        SEnfermeira.getInstance().getEnfermeiras().add(e);
       
        dispose();
         }
    }//GEN-LAST:event_jBCadastrarEnfermeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEnfermeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarEnfermeira;
    private javax.swing.JLabel jDataNascimentoEnfermeira;
    private javax.swing.JLabel jLCPFPaciente;
    private javax.swing.JLabel jLCofen;
    private javax.swing.JLabel jLECEnfermeira;
    private javax.swing.JLabel jLEnderecoEnfermeira;
    private javax.swing.JLabel jLNomeEnfermeira;
    private javax.swing.JLabel jLRGEnfermeira;
    private javax.swing.JLabel jLSexoEnfermeira;
    private javax.swing.JLabel jLTeleEnfermeira;
    private javax.swing.JLabel jLTituloEnfer;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPCadastroEnfermeira;
    private javax.swing.JTextField jTFCPFEnfermeira;
    private javax.swing.JTextField jTFCofen;
    private javax.swing.JTextField jTFDataNascimentoEnfermeira;
    private javax.swing.JTextField jTFEnderecoEnfermeira;
    private javax.swing.JTextField jTFEstadoCivilEnfermeira;
    private javax.swing.JTextField jTFNomeEnfermeiro;
    private javax.swing.JTextField jTFRGEnfermeira;
    private javax.swing.JTextField jTFSetorEnfermeira;
    private javax.swing.JTextField jTFSexoEnfermeira;
    private javax.swing.JTextField jTFTelefoneEnfermeira;
    // End of variables declaration//GEN-END:variables
}
