/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.interfaces;

import br.com.juan.objetos.Pessoa;
import br.com.juan.singleton.SPaciente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class JFResponsavel extends javax.swing.JFrame {

    Pessoa r;

    /**
     * Creates new form JFResponsavel
     */
    public JFResponsavel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastroResponsavel = new javax.swing.JPanel();
        jLECResponsavel = new javax.swing.JLabel();
        jLSexoResponsavel = new javax.swing.JLabel();
        jTFEstadoCivilResponsavel = new javax.swing.JTextField();
        jTFSexoResponsavel = new javax.swing.JTextField();
        jTFCPFResponsavel = new javax.swing.JTextField();
        jTFRGResponsavel = new javax.swing.JTextField();
        jTFNomeResponsavel = new javax.swing.JTextField();
        jTFEnderecoResponsavel = new javax.swing.JTextField();
        jTFDataNascimentoResponsavel = new javax.swing.JTextField();
        jLNomeResponsavel = new javax.swing.JLabel();
        jDataNascimentoMedico = new javax.swing.JLabel();
        jLEnderecoMedico = new javax.swing.JLabel();
        jLRGResponsavel = new javax.swing.JLabel();
        jLCPFResponsavel = new javax.swing.JLabel();
        jLTelResponsavel = new javax.swing.JLabel();
        jTFTelefoneResponsavel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBCadastroResponsavel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPCadastroResponsavel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLECResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLECResponsavel.setText("Estado Civil:");

        jLSexoResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLSexoResponsavel.setText("Sexo (M)(F):");

        jTFEstadoCivilResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCPFResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomeResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFEnderecoResponsavel.setText(" ");

        jTFDataNascimentoResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLNomeResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLNomeResponsavel.setText("Nome:");

        jDataNascimentoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jDataNascimentoMedico.setText("Data de Nascimento: ");

        jLEnderecoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEnderecoMedico.setText("Endereço:");

        jLRGResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLRGResponsavel.setText("RG:");

        jLCPFResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLCPFResponsavel.setText("CPF:");

        jLTelResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTelResponsavel.setText("Telefone:");

        jTFTelefoneResponsavel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPCadastroResponsavelLayout = new javax.swing.GroupLayout(jPCadastroResponsavel);
        jPCadastroResponsavel.setLayout(jPCadastroResponsavelLayout);
        jPCadastroResponsavelLayout.setHorizontalGroup(
            jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroResponsavelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroResponsavelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLNomeResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLEnderecoMedico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLRGResponsavel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLCPFResponsavel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEnderecoResponsavel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFRGResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroResponsavelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroResponsavelLayout.createSequentialGroup()
                                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTelResponsavel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLECResponsavel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10))
                            .addGroup(jPCadastroResponsavelLayout.createSequentialGroup()
                                .addComponent(jLSexoResponsavel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFEstadoCivilResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jTFTelefoneResponsavel)
                            .addComponent(jTFSexoResponsavel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPCadastroResponsavelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDataNascimentoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPCadastroResponsavelLayout.setVerticalGroup(
            jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroResponsavelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNomeResponsavel)
                    .addComponent(jTFTelefoneResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTelResponsavel))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGResponsavel)
                    .addComponent(jTFRGResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEstadoCivilResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLECResponsavel))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFSexoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLSexoResponsavel))
                    .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFCPFResponsavel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCPFResponsavel)))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEnderecoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEnderecoMedico)
                    .addComponent(jTFDataNascimentoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel1.setText("Cadastro de Responsável");

        jBCadastroResponsavel.setText("Cadastrar");
        jBCadastroResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCadastroResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastroResponsavel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPCadastroResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCadastroResponsavel)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastroResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroResponsavelActionPerformed
        String nomeResponsavel = null,teleResponsavel,cpfResponsavel,enderecoResponsavel,ECResponsavel = null,RGResponsavel;
        char SexoResponsavel;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy");
        try {
            ECResponsavel = this.jTFEstadoCivilResponsavel.getText();
            nomeResponsavel = this.jTFNomeResponsavel.getText();
        } catch (StringIndexOutOfBoundsException sioobe) {
            JOptionPane.showMessageDialog(this, "Caracteres inválidos!");
        }
         
         teleResponsavel = this.jTFTelefoneResponsavel.getText();
         cpfResponsavel = this.jTFCPFResponsavel.getText();
         enderecoResponsavel = this.jTFEnderecoResponsavel.getText();
         
         RGResponsavel = this.jTFRGResponsavel.getText();
         SexoResponsavel = this.jTFSexoResponsavel.getText().toUpperCase().charAt(0);
        Date dataNascimentoReponsavel=new Date();
        try {
            dataNascimentoReponsavel = sdf.parse(this.jTFDataNascimentoResponsavel.getText());
        } catch (ParseException ex) {
            Logger.getLogger(JFResponsavel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         r = new Pessoa(nomeResponsavel, teleResponsavel, cpfResponsavel, RGResponsavel, RGResponsavel, ECResponsavel, dataNascimentoReponsavel, SexoResponsavel) {
        };
        SPaciente.getInstance().getResponsavel().add(r);
        dispose();
    }//GEN-LAST:event_jBCadastroResponsavelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
          JFPaciente.getFrames();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFResponsavel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastroResponsavel;
    private javax.swing.JLabel jDataNascimentoMedico;
    private javax.swing.JLabel jLCPFResponsavel;
    private javax.swing.JLabel jLECResponsavel;
    private javax.swing.JLabel jLEnderecoMedico;
    private javax.swing.JLabel jLNomeResponsavel;
    private javax.swing.JLabel jLRGResponsavel;
    private javax.swing.JLabel jLSexoResponsavel;
    private javax.swing.JLabel jLTelResponsavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPCadastroResponsavel;
    private javax.swing.JTextField jTFCPFResponsavel;
    private javax.swing.JTextField jTFDataNascimentoResponsavel;
    private javax.swing.JTextField jTFEnderecoResponsavel;
    private javax.swing.JTextField jTFEstadoCivilResponsavel;
    private javax.swing.JTextField jTFNomeResponsavel;
    private javax.swing.JTextField jTFRGResponsavel;
    private javax.swing.JTextField jTFSexoResponsavel;
    private javax.swing.JTextField jTFTelefoneResponsavel;
    // End of variables declaration//GEN-END:variables
}
