/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.juan.interfaces;

import br.com.juan.objetos.Consulta;
import br.com.juan.objetos.Enfermeira;
import br.com.juan.objetos.Paciente;
import br.com.juan.objetos.Triagem;
import static br.com.juan.objetos.Triagem.CalculoIMC;
import static br.com.juan.objetos.Triagem.diagnosticarFebre;
import br.com.juan.singleton.SEnfermeira;
import br.com.juan.singleton.SPaciente;
import br.com.juan.singleton.STriagem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JFTriagem extends javax.swing.JFrame {
    
    Triagem tr;
    Consulta c;
    Enfermeira e;
    Paciente p;

    /**
     * Creates new form Triagem
     */
    public JFTriagem() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTriagem = new javax.swing.JPanel();
        jLPaciente = new javax.swing.JLabel();
        jLPeso = new javax.swing.JLabel();
        jLAltura = new javax.swing.JLabel();
        jLEnfermeira = new javax.swing.JLabel();
        jLTemperatura = new javax.swing.JLabel();
        jLADD = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLAlergia = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFAltura = new javax.swing.JTextField();
        jTFPeso = new javax.swing.JTextField();
        jTFTemperatura = new javax.swing.JTextField();
        jTFAlergia = new javax.swing.JTextField();
        jTFSintoma = new javax.swing.JTextField();
        jTFPressao = new javax.swing.JTextField();
        jBAddAlergias = new javax.swing.JButton();
        jTFEnfermeira = new javax.swing.JTextField();
        jTFPaciente = new javax.swing.JTextField();
        jLAlergias = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBCadastrarTriagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPTriagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLPaciente.setText("Paciente:");

        jLPeso.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLPeso.setText("Peso:");

        jLAltura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLAltura.setText("Altura:");

        jLEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLEnfermeira.setText("Enfermeira:");

        jLTemperatura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLTemperatura.setText("Temperatura:");

        jLADD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLADD.setText("Adicionar Alergia:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Sintomas:");

        jLAlergia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLAlergia.setText("Alergias:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Pressão:");

        jTFAltura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFPeso.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFTemperatura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFAlergia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSintoma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFPressao.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jBAddAlergias.setText("+");
        jBAddAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddAlergiasActionPerformed(evt);
            }
        });

        jTFEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTFPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTriagemLayout = new javax.swing.GroupLayout(jPTriagem);
        jPTriagem.setLayout(jPTriagemLayout);
        jPTriagemLayout.setHorizontalGroup(
            jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTriagemLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPaciente)
                    .addComponent(jLTemperatura)
                    .addComponent(jLEnfermeira)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFSintoma, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTFPressao)
                    .addComponent(jTFTemperatura)
                    .addComponent(jTFPaciente)
                    .addComponent(jTFEnfermeira))
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTriagemLayout.createSequentialGroup()
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTriagemLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTriagemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPTriagemLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLADD))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTriagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPTriagemLayout.createSequentialGroup()
                                .addComponent(jTFAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAddAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPTriagemLayout.createSequentialGroup()
                                .addComponent(jLAlergia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTriagemLayout.setVerticalGroup(
            jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTriagemLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEnfermeira)
                    .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPeso)
                    .addComponent(jTFEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAltura)
                    .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPaciente)
                    .addComponent(jTFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTemperatura)
                    .addComponent(jLADD))
                .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTriagemLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTFSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTFPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPTriagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAddAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPTriagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAlergia)
                            .addComponent(jLAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel1.setText("Triagem");

        jBCadastrarTriagem.setText("Cadastrar");
        jBCadastrarTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarTriagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCadastrarTriagem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCadastrarTriagem))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPacienteActionPerformed

    private void jBAddAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddAlergiasActionPerformed
        
        String allAlergias = "";
        for (String al :tr.getAlergias()) {
            allAlergias += tr.getAlergias().indexOf(al) + " . " + tr.getAlergias()+ "\n";
        } 
        if (!jTFAlergia.getText().equals("")) {            
            tr.getAlergias().add(jTFAlergia.getText());
            jLAlergias.setText(allAlergias);
        } else {
            JOptionPane.showMessageDialog(this, "Campo em branco, favor digitar! ");
        }
        
    }//GEN-LAST:event_jBAddAlergiasActionPerformed

    private void jBCadastrarTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarTriagemActionPerformed
        
        float temperatura = Float.parseFloat(this.jTFTemperatura.getText());
        float IMC;
        float altura = Float.parseFloat(this.jTFAltura.getText());
        float peso = Float.parseFloat(this.jTFPeso.getText());
        String Sintoma = this.jTFSintoma.getText();
        List<String> alergias = new ArrayList();
        String pressao = this.jTFPressao.getText();
        boolean febre;
        diagnosticarFebre(temperatura);
        CalculoIMC(altura, peso);
        IMC = CalculoIMC(altura, peso);
        
        tr = new Triagem(e, p, pressao, Sintoma, peso, altura, IMC, temperatura, rootPaneCheckingEnabled);
         
        
        STriagem.getInstance().getTriagens().add(tr);
        

    }//GEN-LAST:event_jBCadastrarTriagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTriagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddAlergias;
    private javax.swing.JButton jBCadastrarTriagem;
    private javax.swing.JLabel jLADD;
    private javax.swing.JLabel jLAlergia;
    private javax.swing.JLabel jLAlergias;
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLEnfermeira;
    private javax.swing.JLabel jLPaciente;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPTriagem;
    private javax.swing.JTextField jTFAlergia;
    private javax.swing.JTextField jTFAltura;
    private javax.swing.JTextField jTFEnfermeira;
    private javax.swing.JTextField jTFPaciente;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFPressao;
    private javax.swing.JTextField jTFSintoma;
    private javax.swing.JTextField jTFTemperatura;
    // End of variables declaration//GEN-END:variables
}
